local YAPLGE = {
	draw = require "draw",
	import = require "import"
}
local time=0

function YAPLGE.stringToTable(mapString)
	local mapTable = {}
	local width = #(mapString:match("[^\n]+"))
	for i = 1, width do mapTable[i] = {} end

	local rowindex,columnindex = 1,1

	for i in mapString:gmatch("[^\n]+") do
		column=1
		for character in i:gmatch(".") do
			mapTable[column][rowindex] = character
			column = column + 1
		end
		rowindex = rowindex + 1
	end
	return mapTable
end

function YAPLGE.getTile(x, y, tileSize, map, scale)
	--Where `map` has been generated by `YAPLGE.stringToTable` or is in the same format
	local tile = {
		x,
		y,
		character
	}

	tile.x = math.floor(x/(tileSize*scale))
	tile.y = math.floor(y/(tileSize*scale))

	tile.character = map[tile.x+1][tile.y+1]

	return tile.character
end

return YAPLGE
